---
title: "Mapping Exercise"
author: "Oliver Bott"
date: "14 November 2014"
output:
  html_document:
    fig_caption: yes
    number_sections: no
  pdf_document:
    fig_caption: yes
    number_sections: yes
---

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
# Set working directory. Change as needed
setwd('C:/Users/a6p/Desktop/Uni 2014/E1161 - Collaborative Research/GitHub Clone/Final_Project/')

# file in same directory under html_document css

```

```{r, echo=FALSE, results='asis', warning=FALSE, error=FALSE, message=FALSE}
# Load Dataset.csv from repository
library(RCurl)

# Set SSL certs globally
options(RCurlOptions = list(cainfo = system.file("CurlSSL", "cacert.pem", package = "RCurl")))

# Create dynamic link to Dataset.csv created through the Data_Gathering.R
x <- getURL('https://raw.githubusercontent.com/oliverbott/Final_Project/master/Data/Dataset.csv')
dataset <- read.csv(text = x)

# Clean dataset
dataset$row.names <- NULL
dataset$X <- NULL

```


```{r, echo=FALSE, results='asis', warning=FALSE, error=FALSE, message=FALSE}
##### RENAME datasetfinal when inserting to latest Data_Gathering.R file

library(ggmap)

 places <- c('Vienna', 'Graz', 'Linz', 'Brussels', 'Antwerp', 'Ghent', 'Liege', 'Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt', 'Essen', 'Stuttgart', 'Leipzig', 'Dresden', 'Dortmund', 'Dusseldorf', 'Bremen', 'Hanover', 'Bochum', 'Freiburg', 'Augsburg', 'Bonn', 'Karlsruhe', 'Duisburg', 'Mannheim', 'Aachen', 'Copenhagen', 'Tallinn', 'Madrid', 'Barcelona', 'Valencia', 'Seville', 'Zaragoza', 'Malaga', 'Palmas', 'Bilbao', 'Helsinki', 'Paris', 'Lyon', 'Toulouse', 'Strasbourg', 'Bordeaux', 'Nantes', 'Lille', 'Montpellier', 'Rennes', 'Grenoble', 'Toulon', 'Marseille', 'Nice', 'Rouen', 'Rome', 'Milan', 'Naples', 'Turin', 'Palermo', 'Genova', 'Florence', 'Bari', 'Bologna', 'Catania', 'Venice', 'Mito', 'Tokyo', 'Kofu', 'Nagoya', 'Numazu', 'Osaka', 'Okayama', 'Kurashiki', 'Fukuyama', 'Hiroshima', 'Takamatsu', 'Monterrey', 'Irapuato', 'Hague', 'Amsterdam', 'Rotterdam', 'Utrecht', 'Eindhoven', 'Oslo', 'Lisbon', 'Porto', 'Stockholm', 'Gothenburg', 'Malmo', 'Seattle', 'Portland', 'Minneapolis', 'Milwaukee', 'Madison', 'Buffalo', 'Albany', 'Detroit', 'Boston', 'Chicago', 'Providence', 'Toledo', 'Cleveland', 'Omaha', 'Akron', 'Pittsburgh', 'Harrisburg', 'Philadelphia', 'Columbus', 'Denver', 'Indianapolis', 'Dayton', 'Baltimore', 'Cincinnati', 'Washington', 'Louisville',  'Wichita', 'Richmond', 'Fresno', 'Nashville', 'Tulsa', 'Raleigh', 'Charlotte', 'Albuquerque', 'Memphis', 'Columbia', 'Atlanta', 'Phoenix',  'Dallas', 'Charleston', 'Tucson', 'Austin', 'Jacksonville', 'Houston', 'Orlando', 'Tampa', 'Miami')

location <- geocode(places)

location2 <- data.frame(location, places)

colnames(location2) <- c("lon" , "lat" , "METRO_ID") # Rename columns

datasetfinal <- merge(dataset , location2 , by=c("METRO_ID")) # Merge location vectors with main data set
```



```{r, echo=FALSE, results='asis', warning=FALSE, error=FALSE, message=FALSE}
##### DELETE when inserting to latest Data_Gathering.R file


# Clean data set for potential log transformations

datasetfinal[-c(62, 90), ]
datasetfinal <- datasetfinal[-c(62, 90), ]

# Further, to log the variables medfollowing and hifollowing also delete these rows of these cities
datasetfinal[-c(39, 45, 46, 59, 62, 73, 80, 114, 118, 119), ]
datasetfinal <- datasetfinal[-c(39, 45, 46, 59, 62, 73, 80, 114, 118, 119), ]

# Create dataframe with variables of interest
visdat <- data.frame(datasetfinal$METRO_ID, datasetfinal$Patents, datasetfinal$hifollowing)

```


```{r, echo=FALSE, results='asis', warning=FALSE, error=FALSE, message=FALSE}
##### RENAME when inserting to latest Data_Gathering.R file
##### TAKEN from http://www.r-bloggers.com/r-beginners-plotting-locations-on-to-a-world-map/


library("ggmap")
library(maptools)
library(maps)
 
#Option 1: USING MAPS for world map
map("world", fill=TRUE, col="#f7f7f7", bg="#f7f7f7", ylim=c(-60, 90), mar=c(0,0,0,0))
points(datasetfinal$lon, datasetfinal$lat, col="#de2d26", pch=16)


#Option 2: DOESNT WORK
#map <- get_map(location="Europe", zoom=4)
#mapPoints <- ggmap(map) + geom_points(aes(x = lon, y = lat, size = sqrt(Patents)), data(datasetfinal, alpha = .5)
                                      
#Option3 - this actually works TAKEN FROM http://blog.revolutionanalytics.com/2012/07/making-beautiful-maps-in-r-with-ggmap.html
map.center <- geocode("Europe")
SHmap <- qmap(c(lon=map.center$lon, lat=map.center$lat), source="google", zoom=4)
SHmap + geom_point(aes(x=lon, y=lat), data=datasetfinal) + 
        geom_point(aes(x = lon, y = lat, color=Patents, size=20), 
                   data = datasetfinal)

# color look up in slides
# change 

#Option4 - nope
#G <- gvisGeoChart(datasetfinal, "METRO_ID", "Patents", "hifollowing",
#                options=list(projection="kavrayskiy-vii",
#                             colorAxis="{colors:['#91BFDB', '#FC8D59']}"))
#plot(G)

#G <- gvisGeoChart(datasetfinal, "METRO_ID", "Patents", "hifollowing",
#                   options=list(displayMode="Markers", 
#                   colorAxis="{colors:['purple', 'red', 'orange', 'grey']}",
#                   backgroundColor="lightblue"), chartid="EQ")
#plot(G)

#Option5: Use gvisGeoMap - nope
#world_map <- gvisGeoMap(datasetfinal, locationvar = 'METRO_ID',
#                      numvar = 'Patents')
#plot(world_map)


```

```{r}
#### Google plot for interactive figures


# First try - does not work
library(googleVis)
scat1 <- gvisScatterChart(visdat)
print(scat1, tag = 'Scatterplot')

# Another try - does not work
scat2 <- gvisScatterChart(visdat, options=list(legend="none",
                 lineWidth=2, pointSize=0,
                 title="Title", vAxis="{title:'weight (lbs)'}",
                 hAxis="{title:'height (in)'}", width=300, height=300))
 
plot(scat2)


```

```{r}
# Flow map - does not work

map.market(id=datasetfinal$METRO_ID, area=datasetfinal$Patents, group="METRO_ID", color=datasetfinal$Patents, main="FlowingData Map")

# Simple Dotplot
dotchart(datasetfinal$Patents,labels=row.names(datasetfinal),cex=.7,
    main="Main", 
   xlab="Patents per 10,000 population")

# require(devtools)
# require(Rcpp)
# install_github('ramnathv/rCharts')

# Scatterplot with rCharts, taken from http://rcharts.io/gallery/#visualizationType=scatterplot
# Does not work
n1 <- nPlot(Patents ~ hifollowing, data = datasetfinal, group = "METRO_ID", type = "scatterChart")
n1$addControls("x", value = "nofollowing", values = names(datasetfinal$nofollowing))
n1

# Other rCharts scatterplot, taken from http://rcharts.io/viewer/?6465936#.VHWMY9KG8eg
# Possible to add a best fit line?
d1 <- dPlot(
  Patents ~ hifollowing,
  data = datasetfinal,
  type = "bubble", height=800,
  width=1000,
  bounds = list(x=80, y=8, width=700, height=350)
)
d1$xAxis( type = "addMeasureAxis" )
d1$yAxis( type = "addMeasureAxis" )

d1

```

```{r}
reshape2 - command melt
tidier
```

