# Set working directory
setwd('C:/Sites/Final Project/Final_Project/Data')

# Install and load package RCurl
install.packages("RCurl")
library(RCurl)

options(RCurlOptions = list(cainfo = system.file("CurlSSL", "cacert.pem", package = "RCurl")))

# Create dynamic link to Dataset.csv created through the Data_Gathering.R
x <- getURL('https://raw.githubusercontent.com/oliverbott/Final_Project/master/Data/Dataset.csv')
dataset2 <- read.csv(text = x)

dataset2$X <- NULL # Get rid of extra column

# Add dummy variables

dummyframe <- data.frame (dataset2$METRO_ID, US=c(0), DE=c(0), FR=c(0), JP=c(0))

colnames(dummyframe) <- c("METRO_ID" , "US" , "DE" , "FR" , "JP")



# You can find the city names in order in the Data_Gathering_Final.Rmd (the renaming part)

# US replace 0 by 1
dummyframe$US[dummyframe$METRO_ID %in% "Houston"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Seattle"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Portland"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Minneapolis"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Milwaukee"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Madison"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Buffalo"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Albany"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Detroit"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Boston"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Chicago"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Providence"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Toledo"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Cleveland"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Omaha"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Akron"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Pittsburgh"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Harrisburg"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Philadelphia"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Columbus"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Denver"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Indianapolis"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Dayton"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Baltimore"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Cincinnati"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Washington"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Louisville"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Wichita"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Richmond"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Fresno"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Nashville"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Tulsa"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Raleigh"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Charlotte"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Albuquerque"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Memphis"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Columbia"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Atlanta"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Phoenix"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Dallas"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Charleston"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Tucson"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Austin"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Jacksonville"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Orlando"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Tampa"] <- "1"
dummyframe$US[dummyframe$METRO_ID %in% "Miami"] <- "1"

#... copy code and add all cities

# Germany replace 0 by 1
dummyframe$DE[dummyframe$METRO_ID %in% "Berlin"] <- "1"
dummyframe$DE[dummyframe$METRO_ID %in% "Hamburg"] <- "1"
dummyframe$DE[dummyframe$METRO_ID %in% "Munich"] <- "1"
dummyframe$DE[dummyframe$METRO_ID %in% "Cologne"] <- "1"
dummyframe$DE[dummyframe$METRO_ID %in% "Frankfurt"] <- "1"
dummyframe$DE[dummyframe$METRO_ID %in% "Essen"] <- "1"
dummyframe$DE[dummyframe$METRO_ID %in% "Stuttgart"] <- "1"
dummyframe$DE[dummyframe$METRO_ID %in% "Leipzig"] <- "1"
dummyframe$DE[dummyframe$METRO_ID %in% "Dresden"] <- "1"
dummyframe$DE[dummyframe$METRO_ID %in% "Dortmund"] <- "1"
dummyframe$DE[dummyframe$METRO_ID %in% "Dusseldorf"] <- "1"
dummyframe$DE[dummyframe$METRO_ID %in% "Bremen"] <- "1"
dummyframe$DE[dummyframe$METRO_ID %in% "Hanover"] <- "1"
dummyframe$DE[dummyframe$METRO_ID %in% "Bochum"] <- "1"
dummyframe$DE[dummyframe$METRO_ID %in% "Freiburg"] <- "1"
dummyframe$DE[dummyframe$METRO_ID %in% "Augsburg"] <- "1"
dummyframe$DE[dummyframe$METRO_ID %in% "Bonn"] <- "1"
dummyframe$DE[dummyframe$METRO_ID %in% "Karlsruhe"] <- "1"
dummyframe$DE[dummyframe$METRO_ID %in% "Duisburg"] <- "1"
dummyframe$DE[dummyframe$METRO_ID %in% "Mannheim"] <- "1"
dummyframe$DE[dummyframe$METRO_ID %in% "Aachen"] <- "1"

# France replace 0 by 1
dummyframe$FR[dummyframe$METRO_ID %in% "Paris"] <- "1"
dummyframe$FR[dummyframe$METRO_ID %in% "Lyon"] <- "1"
dummyframe$FR[dummyframe$METRO_ID %in% "Toulouse"] <- "1"
dummyframe$FR[dummyframe$METRO_ID %in% "Strasbourg"] <- "1"
dummyframe$FR[dummyframe$METRO_ID %in% "Bordeaux"] <- "1"
dummyframe$FR[dummyframe$METRO_ID %in% "Nantes"] <- "1"
dummyframe$FR[dummyframe$METRO_ID %in% "Lille"] <- "1"
dummyframe$FR[dummyframe$METRO_ID %in% "Montepellier"] <- "1"
dummyframe$FR[dummyframe$METRO_ID %in% "Rennes"] <- "1"
dummyframe$FR[dummyframe$METRO_ID %in% "Grenoble"] <- "1"
dummyframe$FR[dummyframe$METRO_ID %in% "Toulon"] <- "1"
dummyframe$FR[dummyframe$METRO_ID %in% "Marseille"] <- "1"
dummyframe$FR[dummyframe$METRO_ID %in% "Nice"] <- "1"
dummyframe$FR[dummyframe$METRO_ID %in% "Rouen"] <- "1"


# Japan replace 0 by 1
dummyframe$JP[dummyframe$METRO_ID %in% "Mito"] <- "1"
dummyframe$JP[dummyframe$METRO_ID %in% "Tokyo"] <- "1"
dummyframe$JP[dummyframe$METRO_ID %in% "Kofu"] <- "1"
dummyframe$JP[dummyframe$METRO_ID %in% "Nagoya"] <- "1"
dummyframe$JP[dummyframe$METRO_ID %in% "Numazu"] <- "1"
dummyframe$JP[dummyframe$METRO_ID %in% "Osaka"] <- "1"
dummyframe$JP[dummyframe$METRO_ID %in% "Okayama"] <- "1"
dummyframe$JP[dummyframe$METRO_ID %in% "Kurashiki"] <- "1"
dummyframe$JP[dummyframe$METRO_ID %in% "Fukuyama"] <- "1"
dummyframe$JP[dummyframe$METRO_ID %in% "Hiroshima"] <- "1"
dummyframe$JP[dummyframe$METRO_ID %in% "Takamatsu"] <- "1"


# Merge 

datasetdummy <- merge(dataset2 , dummyframe , by=c("METRO_ID")) 

# Save as .csv

write.csv(dataset, file = "datasetdummy.csv")
# Sync and done.
