---
title: "Website_Test"
author: "Oliver Bott"
date: "Monday, December 08, 2014"
output:
  html_document:
    theme: cosmo
    highlight: kate
---


```{r, echo=FALSE, results='asis', warning=FALSE, error=FALSE, message=FALSE}
# Set working directory

library(RCurl)
library(ggmap)
library(maptools)
library(dplyr)
library(reshape2)
library(maps)
library(stargazer)
library(rCharts)
library(rNVD3)

# Load .csv from GitHub repository
options(RCurlOptions = list(cainfo = system.file("CurlSSL", "cacert.pem", package = "RCurl")))

# Create dynamic link to Dataset.csv created through the Data_Gathering.R
x <- getURL('https://raw.githubusercontent.com/oliverbott/Final_Project/master/Data/Dataset.csv')
dataset <- read.csv(text = x)
dataset$X <- NULL
colnames(dataset) <- c("METRO_ID" , "Patents" , "GDP" , "Population", "Greenspace", "Employment" , "Pollution" , "lon" , "lat" , "Followers" , "1" , "10" , "20" , "30" , "40" , "50" , "60" , "70" , "80" , "90" , "100" , "US" , "DE" , "FR" , "JP" , "hifol")
```

## What are we doing here?

How many groups in this class have done something:

- Interesting?

- Creative?

## City overview - Europe

```{r, echo=FALSE, results='asis', warning=FALSE, error=FALSE, message=FALSE}
countryset <- data.frame (id=1:132)

countryset$METRO_ID <- c('Vienna', 'Graz', 'Linz', 'Brussels', 'Antwerp', 'Ghent', 'Liege', 'Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt', 'Essen', 'Stuttgart', 'Leipzig', 'Dresden', 'Dortmund', 'Dusseldorf', 'Bremen', 'Hanover', 'Bochum', 'Freiburg', 'Augsburg', 'Bonn', 'Karlsruhe', 'Duisburg', 'Mannheim', 'Aachen', 'Copenhagen', 'Tallinn', 'Madrid', 'Barcelona', 'Valencia', 'Seville', 'Zaragoza', 'Malaga', 'Palmas', 'Bilbao', 'Helsinki', 'Paris', 'Lyon', 'Toulouse', 'Strasbourg', 'Bordeaux', 'Nantes', 'Lille', 'Montpellier', 'Rennes', 'Grenoble', 'Toulon', 'Marseille', 'Nice', 'Rouen', 'Rome', 'Naples', 'Turin', 'Palermo', 'Genova', 'Florence', 'Bologna', 'Catania', 'Venice', 'Mito', 'Tokyo', 'Kofu', 'Nagoya', 'Numazu', 'Osaka', 'Okayama', 'Kurashiki', 'Fukuyama', 'Hiroshima', 'Takamatsu', 'Monterrey', 'Irapuato', 'Hague', 'Amsterdam', 'Rotterdam', 'Utrecht', 'Oslo', 'Lisbon', 'Porto', 'Stockholm', 'Gothenburg', 'Malmo', 'Seattle', 'Portland', 'Minneapolis', 'Milwaukee', 'Madison', 'Buffalo', 'Albany', 'Detroit', 'Boston', 'Chicago', 'Providence', 'Toledo', 'Cleveland', 'Omaha', 'Akron', 'Pittsburgh', 'Harrisburg', 'Philadelphia', 'Columbus', 'Denver', 'Indianapolis', 'Dayton', 'Baltimore', 'Cincinnati', 'Washington', 'Louisville',  'Wichita', 'Richmond', 'Fresno', 'Nashville', 'Tulsa', 'Raleigh', 'Charlotte', 'Albuquerque', 'Memphis', 'Columbia', 'Atlanta', 'Phoenix',  'Dallas', 'Charleston', 'Tucson', 'Austin', 'Jacksonville', 'Houston', 'Orlando', 'Tampa', 'Miami')
countryset$id <- NULL

countryset$Country <- c('Austria', 'Austria', 'Austria', 'Belgium', 'Belgium', 'Belgium', 'Belgium', 'Germany', 'Germany', 'Germany', 'Germany', 'Germany', 'Germany', 'Germany', 'Germany', 'Germany', 'Germany', 'Germany', 'Germany', 'Germany', 'Germany', 'Germany', 'Germany', 'Germany', 'Germany', 'Germany', 'Germany', 'Germany', 'Denmark', 'Estonia', 'Spain', 'Spain', 'Spain', 'Spain', 'Spain', 'Spain', 'Spain', 'Spain', 'Finland', 'France', 'France', 'France', 'France', 'France', 'France', 'France', 'France', 'France', 'France', 'France', 'France', 'France', 'France', 'Italy', 'Italy', 'Italy', 'Italy', 'Italy', 'Italy', 'Italy', 'Italy', 'Italy', 'Japan', 'Japan', 'Japan', 'Japan', 'Japan', 'Japan', 'Japan', 'Japan', 'Japan', 'Japan', 'Japan', 'Mexico', 'Mexico', 'Netherlands', 'Netherlands', 'Netherlands', 'Netherlands', 'Norway', 'Portugal', 'Portugal', 'Sweden', 'Sweden', 'Sweden', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States',  'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States',  'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States')

datasetscat <- merge(dataset , countryset , by=c("METRO_ID")) 


n2 <- nPlot(Patents ~ hifol, data = datasetscat, type = "scatterChart", 
    group = "Country")
n2$xAxis(axisLabel = "GitHub Users with >20 Followers")  # add x axis label
n2$yAxis(axisLabel = "Patent Counts")
n2$print("nvd3Scatter", cdn = FALSE, include_assets = TRUE)
```

## When is a GitHub user innovative?

```{r, echo=FALSE, results='asis', warning=FALSE, error=FALSE, message=FALSE}

fol <- dataset

fol$X <- NULL
fol$Patents <- NULL
fol$GDP <- NULL
fol$Population <- NULL
fol$Pollution <- NULL
fol$Greenspace <- NULL
fol$Employment <- NULL
fol$lon <- NULL
fol$lat <- NULL
fol$Followers <- NULL
fol$hifol <- NULL

# Rename variables for melting
colnames(fol) <- c("METRO_ID" , "1-9" , "10-19" , "20" , "30", "40", "50", 
                       "60", "70", "80", "90", "100" , "US" , "DE" , "FR" , "JP")
  # 1 means 1-9 followers, 10 equals 10-19 followers etc.

new <- fol
new_2 <- reshape(new, 
                 varying = c("US", "DE", "FR", "JP"), 
                 v.names = "value",
                 timevar = "Country", 
                 times = c("US", "DE", "FR", "JP"), 
                 new.row.names = 1:1000,
                 direction = "long")

new_2 <- subset(new_2, value>0)
new_2$id <- NULL 
new_2$value <- NULL
new_2$Country <- as.factor(new_2$Country)
x_2 <- split(new_2, new_2$Country)
x_3 <- lapply(x_2, function (x) sapply(x, mean))
x_3 <- data.frame(x_3)
x_3 <- na.omit(x_3)

df <- reshape(x_3, 
                 varying = c("US", "DE", "FR", "JP"), 
                 v.names = "value",
                 timevar = "Country", 
                 times = c("US", "DE", "FR", "JP"), 
                 new.row.names = 1:1000,
                 direction = "long")
variable <- c(1,10,20,30,40,50,60,70,80,90,100, 
              1,10,20,30,40,50,60,70,80,90,100,
              1,10,20,30,40,50,60,70,80,90,100,
              1,10,20,30,40,50,60,70,80,90,100)
df <- data.frame(df, variable)
df$id <- NULL 
df$variable <- as.factor(df$variable)

n1 <- nPlot(value ~ variable, group = "Country", data = df, type = "multiBarChart")
n1$xAxis(axisLabel = "GitHub Follower Categories")  # add x axis label
n1$yAxis(axisLabel = "Count")
n1$print("chart3", cdn = FALSE, include_assets = TRUE)
```
